name: dummymart_jaspr
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.4.3
  freezed_annotation: ^2.4.1
  jaspr: ^0.11.1
  jaspr_riverpod: ^0.3.10
  jaspr_router: ^0.4.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  jaspr_builder: ^0.11.1
  jaspr_web_compilers: ^4.0.9
  json_serializable: ^6.7.1
  lints: ^3.0.0

jaspr:
  mode: server
